/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/rooms/": {
    /** Index */
    get: operations["index_rooms__get"];
  };
  "/rooms/{slug}": {
    /** Details */
    get: operations["details_rooms__slug__get"];
  };
  "/": {
    /** Index */
    get: operations["index__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Puzzle */
    Puzzle: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Completionworth */
      completionWorth: number;
      /**
       * Completed
       * @default false
       */
      completed?: boolean;
      /** State */
      state?: Record<string, never> | null;
      /** Component */
      component: Record<string, never>;
    };
    /** RoomDetail */
    RoomDetail: {
      /** Slug */
      slug: string;
      state: components["schemas"]["TimerState"];
      /** Extratime */
      extraTime: number;
      /** Startedon */
      startedOn?: string | null;
      /** Pausedon */
      pausedOn?: string | null;
      /** Stoppedon */
      stoppedOn?: string | null;
      /** Stage */
      stage?: string | null;
      /**
       * Completion
       * @default 0
       */
      completion?: number;
      /** Activestage */
      activeStage?: number | null;
      /** Stages */
      stages: components["schemas"]["Stage"][];
      /** Name */
      name: string;
      /** Imageurl */
      imageUrl: string;
      /** Basetime */
      baseTime: number;
    };
    /** RoomOverview */
    RoomOverview: {
      /** Slug */
      slug: string;
      state: components["schemas"]["TimerState"];
      /** Extratime */
      extraTime: number;
      /** Startedon */
      startedOn?: string | null;
      /** Pausedon */
      pausedOn?: string | null;
      /** Stoppedon */
      stoppedOn?: string | null;
      /** Stage */
      stage?: string | null;
      /**
       * Completion
       * @default 0
       */
      completion?: number;
      /** Name */
      name: string;
      /** Imageurl */
      imageUrl: string;
      /** Basetime */
      baseTime: number;
      /** Maxcompletion */
      maxCompletion: number;
    };
    /** Stage */
    Stage: {
      /** Slug */
      slug: string;
      /** Puzzles */
      puzzles: components["schemas"]["Puzzle"][];
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
    };
    /**
     * TimerState
     * @enum {string}
     */
    TimerState: "ready" | "active" | "paused" | "finished" | "stopped";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Index */
  index_rooms__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RoomOverview"][];
        };
      };
    };
  };
  /** Details */
  details_rooms__slug__get: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RoomDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Index */
  index__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
