/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/rooms/": {
    /** Index */
    get: operations["index_rooms__get"];
  };
  "/rooms/{slug}": {
    /** Details */
    get: operations["details_rooms__slug__get"];
  };
  "/rooms/components/supported": {
    /** Get Supported Component Types */
    get: operations["get_supported_component_types_rooms_components_supported_get"];
  };
  "/": {
    /** Index */
    get: operations["index__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** DigitalStateComponent */
    DigitalStateComponent: {
      /**
       * Type
       * @constant
       */
      type: "digitalState";
      /** Completeoverrideenabled */
      completeOverrideEnabled: boolean;
      /** Statemap */
      stateMap: {
        [key: string]: string;
      };
      /** Namemap */
      nameMap?: {
        [key: string]: string;
      } | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Puzzle */
    Puzzle: {
      /** Slug */
      slug: string;
      /**
       * Completed
       * @default false
       */
      completed?: boolean;
      /** State */
      state?: Record<string, never> | null;
      /** Name */
      name: string;
      /** Completionworth */
      completionWorth: number;
      /** Component */
      component: components["schemas"]["UnaryDigitalStateComponent"] | components["schemas"]["DigitalStateComponent"] | components["schemas"]["SequenceComponent"] | components["schemas"]["SpeechDetectionComponent"];
    };
    /** RoomDetail */
    RoomDetail: {
      /** Slug */
      slug: string;
      state: components["schemas"]["TimerState"];
      /** Extratime */
      extraTime: number;
      /** Startedon */
      startedOn?: string | null;
      /** Pausedon */
      pausedOn?: string | null;
      /** Stoppedon */
      stoppedOn?: string | null;
      /** Stage */
      stage?: string | null;
      /**
       * Completion
       * @default 0
       */
      completion?: number;
      /** Activestage */
      activeStage?: number | null;
      /** Stages */
      stages: components["schemas"]["Stage"][];
      /** Name */
      name: string;
      /** Imageurl */
      imageUrl: string;
      /** Basetime */
      baseTime: number;
    };
    /** RoomOverview */
    RoomOverview: {
      /** Slug */
      slug: string;
      state: components["schemas"]["TimerState"];
      /** Extratime */
      extraTime: number;
      /** Startedon */
      startedOn?: string | null;
      /** Pausedon */
      pausedOn?: string | null;
      /** Stoppedon */
      stoppedOn?: string | null;
      /** Stage */
      stage?: string | null;
      /**
       * Completion
       * @default 0
       */
      completion?: number;
      /** Name */
      name: string;
      /** Imageurl */
      imageUrl: string;
      /** Basetime */
      baseTime: number;
      /** Maxcompletion */
      maxCompletion: number;
    };
    /** SequenceComponent */
    SequenceComponent: {
      /**
       * Type
       * @constant
       */
      type: "sequence";
      /** Completeoverrideenabled */
      completeOverrideEnabled: boolean;
      /** Statemap */
      stateMap: {
        [key: string]: string;
      };
      /** Namemap */
      nameMap?: {
        [key: string]: string;
      } | null;
      /** Length */
      length: number;
    };
    /** SpeechDetectionComponent */
    SpeechDetectionComponent: {
      /**
       * Type
       * @constant
       */
      type: "speechDetection";
      /** Completeoverrideenabled */
      completeOverrideEnabled: boolean;
      /** Statemap */
      stateMap: {
        [key: string]: string;
      };
      /** Namemap */
      nameMap?: {
        [key: string]: string;
      } | null;
      /** Words */
      words: string[];
    };
    /** Stage */
    Stage: {
      /** Slug */
      slug: string;
      /** Puzzles */
      puzzles: components["schemas"]["Puzzle"][];
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
    };
    /**
     * TimerState
     * @enum {string}
     */
    TimerState: "ready" | "active" | "paused" | "finished" | "stopped";
    /**
     * UIComponentType
     * @enum {string}
     */
    UIComponentType: "unaryDigitalState" | "digitalState" | "sequence" | "speechDetection";
    /** UnaryDigitalStateComponent */
    UnaryDigitalStateComponent: {
      /**
       * Type
       * @constant
       */
      type: "unaryDigitalState";
      /** Completeoverrideenabled */
      completeOverrideEnabled: boolean;
      /** Statemap */
      stateMap: {
        [key: string]: string;
      };
      /** Namemap */
      nameMap?: {
        [key: string]: string;
      } | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Index */
  index_rooms__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RoomOverview"][];
        };
      };
    };
  };
  /** Details */
  details_rooms__slug__get: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RoomDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Supported Component Types */
  get_supported_component_types_rooms_components_supported_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UIComponentType"][];
        };
      };
    };
  };
  /** Index */
  index__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
